### PR TITLE
Modernize qml

### PR DESCRIPTION
**Pull request by mardy**
This removes some warnings, and possibly fixes the issues with Qt 5.12.

### CODE REVIEW

**Review by UniversalSuperBox — APPROVED** [review]
I am approving this, but it is not suited for merge before OTA-13 is released.

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by poVoq** [comment]
Well, did this break the OSK being triggered, or has that been an longer issue already?

**Comment by dobey** [comment]
> Well, did this break the OSK being triggered, or has that been an longer issue already?

This did not. I presume you're talking about accounts using OAuth, and thus embed a browser. There are reports that the QtWebengine upgrade in OTA-13 is when it started happening. However, I just checked on a device where I'm testing Qt 5.12 upgrade, and it is working fine there.

**Comment by poVoq** [comment]
Ah great, so it should be fixed in OTA-15 then. Thanks for the heads-up!

**Pull request merged**
