### PR TITLE
service: support launching the UI even without trusted sessions

### LINKED ISSUE #11: Port the account overlay from MirPromptSession to another option
The [mir-helper](https://github.com/ubports/ubuntu-system-settings-online-accounts/blob/5de06385df2033675be6bbd0ccd11e895a7110a3/online-accounts-service/mir-helper.cpp) creates a MirPromptSession which is used to display the system-settings-online-accounts interface over the app that requested it. Even if that app is system-settings.

The MirPromptSession has no exact analog in the Wayland world. There is a similar enough specification in [xdg-foreign](https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-foreign/xdg-foreign-unstable-v2.xml). Support for this protocol must be added in QtMir, our Mir compositor, then the account overlay must be ported to use it.

Until this request is implemented, it is impossible to use system-settings-online-accounts on Wayland-using devices such as the PinePhone.

This issue is similar to https://github.com/ubports/trust-store/issues/7 and was filed for visibility. Fixing this issue closes https://gitlab.com/ubports/community-ports/pinephone/-/issues/42

### PR DESCRIPTION
**Pull request by mardy**
Fixes: https://github.com/ubports/ubuntu-system-settings-online-accounts/issues/11

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This PR fixes online-accounts dialogs appearing on the PinePhone.

You can install this PR with `sudo ubports-qa install ubuntu-system-settings-online-accounts 17`. Please only do this on the newest version of Ubuntu Touch in the devel channel.

After installing, reboot your device. You may now attempt to sign in to any online account.

**Comment by lgtrombetta** [comment]
> This PR fixes online-accounts dialogs appearing on the PinePhone.
> 
> You can install this PR with `sudo ubports-qa install ubuntu-system-settings-online-accounts 17`. Please only do this on the newest version of Ubuntu Touch in the devel channel.
> 
> After installing, reboot your device. You may now attempt to sign in to any online account.

Works great for me on the kernelupgrade channel :)

**Comment by eighthourblink** [comment]
`sudo ubports-qa install ubuntu-system-settings-online-accounts 17`
Installed the following and rebooted the phone. By going to Settings > Accounts > Google - it prompted me to use another browser due to unsecured issues / couldnt sign in.

`This browser or app may not be secure
Try using a different browser. If you're already using a supported browser, you can refresh your screen and try again to sign in`

Running : Ubuntu Touch Dev Channel Update 556

**Comment by mardy** [comment]
> `sudo ubports-qa install ubuntu-system-settings-online-accounts 17`
> Installed the following and rebooted the phone. By going to Settings > Accounts > Google - it prompted me to use another browser due to unsecured issues / couldnt sign in.

That's expected, it's another bug, which is addressed by https://github.com/ubports/ubuntu-system-settings-online-accounts/pull/16 and https://github.com/ubports/account-plugins/pull/45

**Comment by whoeveritis** [comment]
quite a pity with nextcloud this works only for calendar but not contacts.

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
