### PR TITLE
UI tweaks and bumped qtquick version

### PR DESCRIPTION
**Pull request by cibersheep**
Small color tweaks and bumped qtquick version

### CODE REVIEW

**Comment by mariogrip** [comment]
Im not sure if bumping qtquick version is needed? as that would remove the backwards compatibility?

**Comment by cibersheep** [comment]
Supposedly 2.9 would have some bugs fixed and would be a bit quicker that 2.0

Mostly all of the system has 2.4 version though. What are we keeping backwards compatibility with?

What do you want me to do?
- I could bump to 2.4 as the rest of the system
- Leave 2.0
- Other?

**Comment by UniversalSuperBox** [comment]
The UITK only supports Qt 5.9 and above (see the README in [ubports/ubuntu-ui-toolkit](https://github.com/ubports/ubuntu-ui-toolkit)), so it is safe to bump.

**Comment by mariogrip** [comment]
> The UITK only supports Qt 5.9 and above (see the README in [ubports/ubuntu-ui-toolkit](https://github.com/ubports/ubuntu-ui-toolkit)), so it is safe to bump.

You're right, this is probably ok

**Pull request merged**
