### PR TITLE
Make ussoa build again

### PR DESCRIPTION
**Pull request by dobey**
This cleans up some of the debian packaging a bit and gets the repo building again.

### CODE REVIEW

**Review by mardy — CHANGES_REQUESTED** [review]
The `QT_SELECT` variable in `debian/rules` breaks the build in crossbuilder, can we remove it?

**Comment by dobey** [comment]
> The `QT_SELECT` variable in `debian/rules` breaks the build in crossbuilder, can we remove it?

How so? This is the correct way to build it.

**Comment by mardy** [comment]
> > The `QT_SELECT` variable in `debian/rules` breaks the build in crossbuilder, can we remove it?
> 
> How so? This is the correct way to build it.

Because `crossbuilder` sets the `QT_SELECT` variable ([here](https://github.com/ubports/crossbuilder/blob/master/crossbuilder#L337)) to a profile that allows cross-compilation. But if you restore the dependency on `qt5-default`, that will work both in the CI and in crossbuilder.

**Comment by mardy** [comment]
My concern with crossbuilder can be addressed with https://github.com/ubports/crossbuilder/pull/44, so I'm fine with merging this.

**Review by mardy — APPROVED** [review]

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
